// Equipamento geral de Ordem Paranormal RPG: acessórios, kits, explosivos,
// itens operacionais e paranormais e munições (LR cap. 3, p. 59 e 63–67,
// Tab. 3.4, 3.8 e 3.10), as regras de espaço da carga (LR p. 53) e os itens
// novos do Sobrevivendo ao Horror (SaH p. 37–45 e 94, Tab. 1.5 na p. 40).
// Conferido nas páginas dos dois livros e no C.R.I.S. Armas, proteções,
// modificações e itens amaldiçoados têm catálogos próprios.
//
// - `efeitos` valem enquanto o personagem tem o item; 'empunhado' e 'vestido'
//   em `especial` dizem se ele precisa estar na mão ou no corpo. O que só
//   acontece ao usar o item (ação, PE, gasto) fica em `especial`.
// - Bônus de itens na mesma perícia não se somam: vale um só (LR p. 63).
// - "(Elemento)" no nome ou "elemento à escolha" em `especial`: o elemento é
//   escolhido ao requisitar o item.
// - Munição: `usos` = cenas que o pacote dura (foguete e dardos: disparos). Com
//   a contagem de munição (regra opcional, LR p. 174), cada pacote tem 20 ataques.
import type { Equipamento } from '../tipos';

const LR = (pagina: number) => ({ fonte: 'LR' as const, pagina });
const SAH = (pagina: number) => ({ fonte: 'SaH' as const, pagina });

const CONTAGEM = 'contagem de munição (opcional, LR p. 174): 20 ataques';
const GRANADA = ['consumível', 'empunhado', 'ação padrão: lança num ponto em alcance médio; raio de 6 m'];
const MEDICAMENTO = ['consumível', 'ação padrão, em você ou num ser adjacente'];
const CATALISADOR = ['consumível', 'empunhado', 'elemento à escolha: Sangue, Morte, Conhecimento ou Energia', 'um catalisador por ritual', 'não pode ser improvisado; pode ser fabricado em campo (SaH p. 94)'];

export const EQUIPAMENTOS: Equipamento[] = [
  // ── Espaço na carga (LR p. 53). O padrão é 1 espaço; armas de duas mãos e
  // proteções leves ocupam 2 e proteções pesadas, 5 (nos seus catálogos).
  { id: 'item-desprezivel', nome: 'Item Desprezível', ref: LR(53), categoria: 0, espacos: 0, grupo: 'outro', especial: ['ex.: caneta, moeda', 'a critério do mestre'], resumo: 'Coisas de peso e volume desprezíveis, como uma caneta ou uma moeda, não ocupam espaço, se o mestre concordar.' },
  { id: 'recipiente-simples', nome: 'Recipiente Simples', ref: LR(53), categoria: 0, espacos: 0, grupo: 'outro', especial: ['ex.: a mochila comum, o coldre da pistola, a bainha da espada', 'recipiente com benefício próprio ocupa espaço (ex.: bandoleira)'], resumo: 'A mochila comum e os recipientes que só servem para levar outro item não ocupam espaço; o coldre já conta no espaço da pistola.' },
  { id: 'item-volumoso', nome: 'Item Volumoso', ref: LR(53), categoria: 0, espacos: 2, grupo: 'outro', especial: ['ex.: mala de viagem'], resumo: 'Coisa grande ou pesada, como uma mala de viagem, ocupa 2 espaços.' },
  { id: 'item-muito-volumoso', nome: 'Item Muito Volumoso', ref: LR(53), categoria: 0, espacos: 5, grupo: 'outro', especial: ['ex.: caixote'], resumo: 'Coisa muito grande ou pesada, como um caixote, ocupa 5 espaços.' },
  { id: 'item-extremamente-volumoso', nome: 'Item Extremamente Volumoso', ref: LR(53), categoria: 0, espacos: 10, grupo: 'outro', especial: ['ex.: uma pessoa, como um agente inconsciente', 'maior que isso: mais espaços ou impossível de levar, a critério do mestre'], resumo: 'Carga enorme, como uma pessoa desacordada, ocupa 10 espaços; algo maior pode ocupar mais ou nem dar para levar.' },

  // ── Munições (LR p. 59, Tab. 3.4). O pacote dura as cenas indicadas, não
  // importa quantos disparos.
  { id: 'balas-curtas', nome: 'Balas Curtas', ref: LR(59), categoria: 0, espacos: 1, grupo: 'municao', usos: 2, especial: ['dura 2 cenas', 'pistolas, revólveres e submetralhadoras', CONTAGEM], resumo: 'Munição básica de pistolas, revólveres e submetralhadoras; o pacote dura duas cenas.' },
  { id: 'balas-longas', nome: 'Balas Longas', ref: LR(59), categoria: 1, espacos: 1, grupo: 'municao', usos: 1, especial: ['dura 1 cena', 'fuzis e metralhadoras', CONTAGEM], resumo: 'Munição maior e mais forte, de fuzis e metralhadoras; o pacote dura uma cena.' },
  { id: 'cartuchos', nome: 'Cartuchos', ref: LR(59), categoria: 1, espacos: 1, grupo: 'municao', usos: 1, especial: ['dura 1 cena', 'espingardas', CONTAGEM], resumo: 'Cartuchos com esferas de chumbo para espingardas; o pacote dura uma cena.' },
  { id: 'combustivel', nome: 'Combustível', ref: LR(59), categoria: 1, espacos: 1, grupo: 'municao', usos: 1, especial: ['dura 1 cena', 'lança-chamas', CONTAGEM], resumo: 'Tanque de combustível do lança-chamas; dura uma cena.' },
  { id: 'flechas', nome: 'Flechas', ref: LR(59), categoria: 0, espacos: 1, grupo: 'municao', especial: ['dura a missão inteira', 'arcos e bestas', CONTAGEM], resumo: 'Flechas de arcos e bestas; como dá para recolhê-las após cada combate, o pacote dura a missão toda.' },
  { id: 'foguete', nome: 'Foguete', ref: LR(59), categoria: 1, espacos: 1, grupo: 'municao', usos: 1, especial: ['1 disparo', 'bazuca'], resumo: 'Foguete de bazuca; cada um vale um só disparo, então é preciso levar vários.' },

  // ── Acessórios (LR p. 63). Um kit por perícia que o exige (LR p. 40).
  { id: 'utensilio', nome: 'Utensílio', ref: LR(63), categoria: 1, espacos: 1, grupo: 'utensilio', efeitos: [{ alvo: 'pericia', pericia: 'escolhida', valor: 2 }], especial: ['empunhado', 'perícia escolhida ao adquirir, exceto Luta e Pontaria', 'o mestre decide se o item é apropriado'], resumo: 'Objeto comum com uma utilidade, como lupa, celular ou notebook: +2 numa perícia escolhida ao adquiri-lo, se estiver na mão.' },
  { id: 'vestimenta', nome: 'Vestimenta', ref: LR(63), categoria: 1, espacos: 1, grupo: 'vestimenta', efeitos: [{ alvo: 'pericia', pericia: 'escolhida', valor: 2 }], especial: ['vestido', 'perícia aprovada pelo mestre, exceto Luta e Pontaria', 'só 2 vestimentas dão bônus ao mesmo tempo', 'vestir ou despir: ação completa'], resumo: 'Roupa que dá +2 numa perícia, como botas militares em Atletismo ou terno em Diplomacia; só duas valem de uma vez.' },
  { id: 'kit-de-ladrao', nome: 'Kit de Ladrão', ref: LR(63), categoria: 0, espacos: 1, grupo: 'kit', kitDe: 'crime', especial: ['exigido para arrombar e sabotar (Crime, LR p. 44)', 'sem o kit: −5 no teste'], resumo: 'Ferramentas que Crime pede para arrombar e sabotar; sem elas, esses testes sofrem −5.' },
  { id: 'kit-de-disfarces', nome: 'Kit de Disfarces', ref: LR(63), categoria: 0, espacos: 1, grupo: 'kit', kitDe: 'enganacao', especial: ['exigido para disfarce (Enganação, LR p. 44)', 'sem o kit: −5 no teste'], resumo: 'Material que Enganação pede para montar um disfarce; sem ele, o teste sofre −5.' },
  { id: 'kit-de-medicina', nome: 'Kit de Medicina', ref: LR(63), categoria: 0, espacos: 1, grupo: 'kit', kitDe: 'medicina', especial: ['exigido em todos os usos de Medicina (LR p. 46)', 'sem o kit: −5 no teste'], resumo: 'Material que todo uso de Medicina pede; sem ele, o teste sofre −5.' },
  { id: 'kit-de-eletronica', nome: 'Kit de Eletrônica', ref: LR(63), categoria: 0, espacos: 1, grupo: 'kit', kitDe: 'tecnologia', especial: ['exigido para operar dispositivo (Tecnologia, LR p. 49)', 'sem o kit: −5 no teste', 'o livro também o chama de kit de tecnologia (LR p. 64)'], resumo: 'Ferramentas que Tecnologia pede para operar dispositivos; sem elas, o teste sofre −5.' },

  // ── Explosivos (LR p. 64). Granada: empunhe e gaste uma ação padrão para
  // lançá-la num ponto em alcance médio; afeta um raio de 6 m.
  { id: 'granada-de-atordoamento', nome: 'Granada de Atordoamento', ref: LR(64), categoria: 0, espacos: 1, grupo: 'explosivo', usos: 1, especial: [...GRANADA, 'atordoado por 1 rodada (Fortitude DT Agi reduz para ofuscado e surdo por 1 rodada)'], resumo: 'Estouro com clarão: quem está no raio fica atordoado por uma rodada, ou só ofuscado e surdo se resistir.' },
  { id: 'granada-de-fragmentacao', nome: 'Granada de Fragmentação', ref: LR(64), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: [...GRANADA, '8d6 de perfuração (Reflexos DT Agi reduz à metade)'], resumo: 'Lança estilhaços por todo o raio: 8d6 de perfuração, ou metade para quem passar em Reflexos.' },
  { id: 'granada-de-fumaca', nome: 'Granada de Fumaça', ref: LR(64), categoria: 0, espacos: 1, grupo: 'explosivo', usos: 1, especial: [...GRANADA, 'cegos e com camuflagem total; dura 2 rodadas'], resumo: 'Enche o raio de fumaça escura por duas rodadas; quem está dentro fica cego e com camuflagem total.' },
  { id: 'granada-incendiaria', nome: 'Granada Incendiária', ref: LR(64), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: [...GRANADA, '6d6 de fogo e em chamas (Reflexos DT Agi reduz à metade e evita em chamas)'], resumo: 'Espalha labaredas pelo raio: 6d6 de fogo e em chamas; Reflexos reduz o dano à metade e evita as chamas.' },
  { id: 'mina-antipessoal', nome: 'Mina Antipessoal', ref: LR(64), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: ['consumível', 'instalar: ação completa e Tática DT 15 (falhou: a mina é gasta e não funciona)', 'detonar: ação padrão, a até alcance longo', 'cone de 6 m: 12d6 de perfuração (Reflexos DT Int reduz à metade)', 'achar: Percepção com DT igual ao teste de instalação'], resumo: 'Mina de controle remoto posta no chão; ao explodir, lança bolas de aço num cone de 6 m (12d6 de perfuração).' },

  // ── Itens operacionais (LR p. 64–66)
  { id: 'algemas', nome: 'Algemas', ref: LR(64), categoria: 0, espacos: 1, grupo: 'operacional', especial: ['empunhado', 'prender quem não está indefeso: agarrar e vencer outro teste de agarrar', 'dois pulsos: −5 em testes que usam as mãos e não conjura rituais', 'ou um pulso num objeto fixo adjacente: não se move', 'escapar: Acrobacia DT 30 (ou ter a chave)'], resumo: 'Algemas de aço para prender os pulsos de alguém agarrado, ou um pulso a um objeto fixo.' },
  { id: 'arpeu', nome: 'Arpéu', ref: LR(65), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'pericia', pericia: 'atletismo', valor: 5, condicional: 'para subir um muro com a corda do arpéu' }], especial: ['prender o gancho: Pontaria DT 15'], resumo: 'Gancho de aço na ponta de uma corda para se prender em muros, janelas e parapeitos e ajudar na escalada.' },
  { id: 'bandoleira', nome: 'Bandoleira', ref: LR(65), categoria: 1, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: 'uma vez por rodada, saca ou guarda um item como ação livre' }], especial: ['vestido'], resumo: 'Cinto com bolsos e alças: uma vez por rodada, sacar ou guardar um item vira ação livre.' },
  { id: 'binoculos', nome: 'Binóculos', ref: LR(65), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'pericia', pericia: 'percepcao', valor: 5, condicional: 'para observar coisas distantes' }], especial: ['empunhado'], resumo: 'Binóculos militares para enxergar melhor o que está longe.' },
  { id: 'bloqueador-de-sinal', nome: 'Bloqueador de Sinal', ref: LR(65), categoria: 1, espacos: 1, grupo: 'operacional', especial: ['celulares em alcance médio não se conectam'], resumo: 'Aparelho compacto que polui a frequência de rádio e impede os celulares próximos de se conectarem.' },
  { id: 'cicatrizante', nome: 'Cicatrizante', ref: LR(65), categoria: 1, espacos: 1, grupo: 'operacional', usos: 1, especial: ['consumível', 'ação padrão: cura 2d8+2 PV em você ou num ser adjacente'], resumo: 'Spray de remédio cicatrizante: numa ação padrão, cura 2d8+2 PV em você ou em alguém ao lado e acaba.' },
  { id: 'corda', nome: 'Corda', ref: LR(65), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'pericia', pericia: 'atletismo', valor: 5, condicional: 'para descer um buraco ou um prédio' }], especial: ['10 m'], resumo: 'Rolo de dez metros de corda resistente, útil para descer buracos e prédios ou amarrar alguém desacordado.' },
  { id: 'equipamento-de-sobrevivencia', nome: 'Equipamento de Sobrevivência', ref: LR(65), categoria: 0, espacos: 2, grupo: 'operacional', efeitos: [{ alvo: 'pericia', pericia: 'sobrevivencia', valor: 5, condicional: 'para acampar e se orientar' }, { alvo: 'nota', texto: 'acampar e se orientar com Sobrevivência mesmo sem treino' }], resumo: 'Mochila com saco de dormir, panelas, GPS e outros itens para acampar e se orientar no mato, mesmo sem treino.' },
  { id: 'lanterna-tatica', nome: 'Lanterna Tática', ref: LR(65), categoria: 1, espacos: 1, grupo: 'operacional', especial: ['empunhado', 'ação de movimento: ofusca por 1 rodada um ser em alcance curto, que fica imune a ela pelo resto da cena'], resumo: 'Ilumina lugares escuros e pode ofuscar por um instante quem receber a luz nos olhos.' },
  { id: 'mascara-de-gas', nome: 'Máscara de Gás', ref: LR(66), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'pericia', pericia: 'fortitude', valor: 10, condicional: 'contra efeitos que dependem da respiração' }], especial: ['vestido'], resumo: 'Máscara com filtro que cobre o rosto inteiro e protege do que se respira.' },
  { id: 'mochila-militar', nome: 'Mochila Militar', ref: LR(66), categoria: 1, espacos: 0, grupo: 'operacional', efeitos: [{ alvo: 'espacos', valor: 2 }], especial: ['não ocupa espaço (a tabela marca *)'], resumo: 'Mochila leve e de boa qualidade: não ocupa espaço e aumenta a carga em 2 espaços.' },
  { id: 'oculos-de-visao-termica', nome: 'Óculos de Visão Térmica', ref: LR(66), categoria: 1, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: 'sem penalidade em testes por camuflagem' }], especial: ['vestido'], resumo: 'Óculos que mostram o calor dos corpos e anulam a penalidade por camuflagem nos testes.' },
  { id: 'pe-de-cabra', nome: 'Pé de Cabra', ref: LR(66), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: '+5 em testes de Força para arrombar portas' }], especial: ['empunhado', 'em combate, conta como um bastão'], resumo: 'Barra de ferro que ajuda a forçar portas e serve de bastão numa briga.' },
  { id: 'pistola-de-dardos', nome: 'Pistola de Dardos', ref: LR(66), categoria: 1, espacos: 1, grupo: 'operacional', usos: 2, especial: ['empunhado', 'ataque à distância', 'acertou: inconsciente até o fim da cena (Fortitude DT Agi reduz para desprevenido e lento por 1 rodada)', 'vem com 2 dardos; mais dardos: Caixa de Dardos'], resumo: 'Dispara dardos com sonífero: quem é atingido apaga até o fim da cena, a menos que resista.' },
  { id: 'caixa-de-dardos', nome: 'Caixa de Dardos', ref: LR(66), categoria: 0, espacos: 1, grupo: 'municao', usos: 2, especial: ['2 dardos para a pistola de dardos'], resumo: 'Caixa extra com dois dardos soníferos para a pistola de dardos.' },
  { id: 'pistola-sinalizadora', nome: 'Pistola Sinalizadora', ref: LR(66), categoria: 0, espacos: 1, grupo: 'operacional', usos: 1, especial: ['empunhado', 'uma vez: arma de disparo leve, alcance curto, 2d6 de fogo'], resumo: 'Dispara um sinalizador luminoso para chamar os outros; numa emergência, serve uma vez como arma.' },
  { id: 'soqueira', nome: 'Soqueira', ref: LR(66), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'dano', escopo: 'desarmado', valor: 1 }], especial: ['empunhado', 'aceita modificações de armas corpo a corpo, que valem nos ataques desarmados'], resumo: 'Peça de metal usada entre os dedos que deixa os socos mais perigosos e aceita modificações de arma.' },
  { id: 'spray-de-pimenta', nome: 'Spray de Pimenta', ref: LR(66), categoria: 1, espacos: 1, grupo: 'operacional', usos: 2, especial: ['empunhado', 'ação padrão contra um ser adjacente: cego por 1d4 rodadas (Fortitude DT Agi evita)'], resumo: 'Jato químico que arde e faz lacrimejar, cegando por alguns instantes um ser ao lado; a carga dá dois usos.' },
  { id: 'taser', nome: 'Taser', ref: LR(66), categoria: 1, espacos: 1, grupo: 'operacional', usos: 2, especial: ['empunhado', 'ação padrão contra um ser adjacente: 1d6 de eletricidade e atordoado por 1 rodada (Fortitude DT Agi evita)'], resumo: 'Aparelho de choque que fere e atordoa um ser ao lado; a bateria dá dois usos.' },
  { id: 'traje-hazmat', nome: 'Traje Hazmat', ref: LR(66), categoria: 1, espacos: 2, grupo: 'operacional', efeitos: [{ alvo: 'resistenciaTeste', valor: 5, condicional: 'contra efeitos ambientais' }, { alvo: 'resistencia', dano: 'quimico', valor: 10 }], especial: ['vestido'], resumo: 'Roupa impermeável de corpo inteiro que isola o usuário de materiais tóxicos.' },

  // ── Itens paranormais (LR p. 66–67, Tab. 3.10)
  { id: 'amarras-de-elemento', nome: 'Amarras de (Elemento)', ref: LR(66), categoria: 2, espacos: 1, grupo: 'paranormal', especial: ['elemento à escolha', 'armadilha: gasta as amarras, ação completa e 2 PE; área de 3 × 3 m; quem entra faz Reflexos (DT Int) ou fica imóvel até o fim da cena; o espaço vira terreno difícil', 'laçar: ação padrão e 1 PE, uma criatura em alcance curto; Vontade (DT Agi) ou paralisada até o início do próximo turno dela; manter: 1 PE por rodada'], resumo: 'Cordas ou correntes feitas de um elemento para prender criaturas vulneráveis a ele, numa armadilha ou num laço.' },
  { id: 'camera-de-aura-paranormal', nome: 'Câmera de Aura Paranormal', ref: LR(66), categoria: 2, espacos: 1, grupo: 'paranormal', especial: ['foto: ação padrão e 1 PE', 'a foto sai na hora e mostra auras paranormais na cor do elemento'], resumo: 'Câmera instantânea com sigilos que revela nas fotos as auras paranormais de pessoas e objetos, na cor do elemento.' },
  { id: 'componentes-ritualisticos-de-elemento', nome: 'Componentes Ritualísticos de (Elemento)', ref: LR(66), categoria: 0, espacos: 1, grupo: 'paranormal', especial: ['um conjunto por elemento: Sangue, Morte, Conhecimento ou Energia (não há de Medo)', 'exigidos para conjurar os rituais do elemento'], resumo: 'Objetos ligados a um elemento, como ossos para Morte ou pilhas para Energia, necessários para conjurar os rituais dele.' },
  { id: 'emissor-de-pulsos-paranormais', nome: 'Emissor de Pulsos Paranormais', ref: LR(67), categoria: 2, espacos: 1, grupo: 'paranormal', especial: ['ativar: ação completa e 1 PE', 'pulso de um elemento: atrai criaturas dele e afasta as do elemento oposto (Vontade DT Pre evita)'], resumo: 'Caixinha coberta de sigilos que serve de isca: atrai criaturas de um elemento e espanta as do elemento oposto.' },
  { id: 'escuta-de-ruidos-paranormais', nome: 'Escuta de Ruídos Paranormais', ref: LR(67), categoria: 2, espacos: 1, grupo: 'paranormal', efeitos: [{ alvo: 'pericia', pericia: 'ocultismo', valor: 5, condicional: 'ouvindo a gravação, para identificar criatura' }], especial: ['ativar: ação completa e 2 PE; grava por até 24 horas'], resumo: 'Microfone espião que grava ruídos do Outro Lado; ouvir a gravação ajuda a identificar a criatura.' },
  // Sem linha na Tab. 3.10: categoria I como decidiu o C.R.I.S; espaço pelo padrão (1).
  { id: 'medidor-de-estabilidade-da-membrana', nome: 'Medidor de Estabilidade da Membrana', ref: LR(67), categoria: 1, espacos: 1, grupo: 'paranormal', especial: ['exige Ocultismo treinado', 'fora da Tab. 3.10: o mestre confirma a categoria'], resumo: 'Conjunto de medidores com que alguém treinado em Ocultismo avalia a Membrana de um lugar e a chance de algo se manifestar ali.' },
  { id: 'scanner-de-manifestacao-paranormal-de-elemento', nome: 'Scanner de Manifestação Paranormal de (Elemento)', ref: LR(67), categoria: 2, espacos: 1, grupo: 'paranormal', especial: ['elemento à escolha', 'ativar: ação padrão; gasta 1 PE por rodada ligado', 'dá a direção das manifestações do elemento em alcance longo (inclui criaturas que o têm como complemento)'], resumo: 'Aparelho ligado a pequenos objetos amaldiçoados que aponta a direção das manifestações de um elemento, gastando PE enquanto está ligado.' },

  // ══ Sobrevivendo ao Horror (sem resumo) ══

  // Munição do estilingue (SaH p. 37): "ocupa o mesmo espaço do estilingue".
  { id: 'bolinhas', nome: 'Bolinhas', ref: SAH(37), categoria: 0, espacos: 0, grupo: 'municao', especial: ['estilingue', 'dura a missão inteira', 'reaproveitáveis; na falta, pedrinhas', 'ocupa o mesmo espaço do estilingue'] },

  // Acessórios (SaH p. 39)
  { id: 'amuleto-sagrado', nome: 'Amuleto Sagrado', ref: SAH(39), categoria: 0, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'religiao', valor: 2 }, { alvo: 'pericia', pericia: 'vontade', valor: 2 }], especial: ['utensílio especial', 'vestido', 'ocupa o espaço de um item vestido'] },
  { id: 'celular', nome: 'Celular', ref: SAH(39), categoria: 0, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'todas', valor: 2, condicional: 'com internet, em testes para adquirir informações' }], especial: ['utensílio especial', 'empunhado', 'lanterna fraca: cone de 4,5 m'] },
  { id: 'chave-de-fenda-universal', nome: 'Chave de Fenda Universal', ref: SAH(39), categoria: 0, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'todas', valor: 2, condicional: 'para criar ou reparar objetos, ou como item de apoio em situações especiais' }], especial: ['empunhado'] },
  { id: 'chaves', nome: 'Chaves', ref: SAH(39), categoria: 0, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'furtividade', valor: 2, condicional: 'na rodada em que usa o barulho das chaves para distrair alguém' }] },
  { id: 'documentos-falsos', nome: 'Documentos Falsos', ref: SAH(39), categoria: 1, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'diplomacia', valor: 2, condicional: 'para se passar pela pessoa dos documentos' }, { alvo: 'pericia', pericia: 'enganacao', valor: 2, condicional: 'para se passar pela pessoa dos documentos' }, { alvo: 'pericia', pericia: 'intimidacao', valor: 2, condicional: 'para se passar pela pessoa dos documentos' }] },
  { id: 'manual-operacional', nome: 'Manual Operacional', ref: SAH(39), categoria: 1, espacos: 1, grupo: 'acessorio', efeitos: [{ alvo: 'treino', pericia: 'escolhida', condicional: 'depois de uma ação de interlúdio lendo o manual, até o próximo interlúdio' }], especial: ['um manual por perícia', 'só um manual vale por vez', 'aprimorado (LR p. 64): também +5 na perícia'] },
  { id: 'notebook', nome: 'Notebook', ref: SAH(39), categoria: 0, espacos: 2, grupo: 'acessorio', efeitos: [{ alvo: 'pericia', pericia: 'todas', valor: 2, condicional: 'com internet, em testes para adquirir informações' }, { alvo: 'nota', texto: 'relaxar no interlúdio recupera 1 de Sanidade a mais' }], especial: ['utensílio especial', 'empunhado', 'a tela ilumina um cone de 4,5 m', 'tablets contam como notebook'] },

  // Explosivos (SaH p. 41)
  { id: 'dinamite', nome: 'Dinamite', ref: SAH(41), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: ['consumível', 'empunhado', 'ação padrão: acende e lança num ponto em alcance médio; raio de 6 m', '4d6 de impacto e 4d6 de fogo e em chamas (Reflexos DT Agi reduz à metade e evita em chamas)'] },
  { id: 'explosivo-plastico', nome: 'Explosivo Plástico', ref: SAH(41), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: ['consumível', 'preparar e grudar: 2 rodadas', 'detonar: detonador (ação livre, até alcance longo) ou 1 ou mais de dano de fogo ou eletricidade', 'raio de 3 m: 16d6 de impacto (Reflexos DT Int reduz à metade)', 'especialista (treinado em Crime ou numa Profissão adequada): dobro de dano em objetos e estruturas, ignorando a RD'] },
  { id: 'galao-vermelho', nome: 'Galão Vermelho', ref: SAH(41), categoria: 0, espacos: 2, grupo: 'explosivo', usos: 1, especial: ['explode ao sofrer dano de fogo ou balístico', 'esfera de 6 m: 12d6 de fogo e em chamas (Reflexos DT 25 reduz à metade e evita a condição)', 'a área segue em chamas (1d6 de fogo por rodada) até ser apagada ou a cena acabar'] },
  { id: 'granada-de-gas-sonifero', nome: 'Granada de Gás Sonífero', ref: SAH(41), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: [...GRANADA, 'o gás fica 2 rodadas', 'quem começa o turno na área: inconsciente e caído; em atividade intensa, exausto por 1 rodada e depois fatigado', 'Fortitude DT Agi reduz para fatigado por 1d4 rodadas'] },
  { id: 'granada-de-pem', nome: 'Granada de PEM', ref: SAH(41), categoria: 1, espacos: 1, grupo: 'explosivo', usos: 1, especial: ['consumível', 'empunhado', 'ação padrão: lança num ponto em alcance médio', 'raio de 18 m: desliga equipamentos elétricos até o fim da cena', 'criaturas de Energia: 6d6 de impacto e atordoadas por 1 rodada, uma vez por cena (Fortitude DT Agi reduz à metade e evita a condição)'] },

  // Itens operacionais (SaH p. 42–44)
  { id: 'alarme-de-movimento', nome: 'Alarme de Movimento', ref: SAH(42), categoria: 0, espacos: 1, grupo: 'operacional', especial: ['posicionar e ativar: ação completa', 'avisa o controle de movimento num cone de 30 m (padrão: ser Pequeno ou maior)', 'aviso discreto ou sonoro'] },
  { id: 'alimento-energetico', nome: 'Alimento Energético', ref: SAH(42), categoria: 2, espacos: 1, grupo: 'operacional', usos: 1, especial: ['consumível', 'ação padrão: recupera 1d4 PE'] },
  { id: 'aplicador-de-medicamentos', nome: 'Aplicador de Medicamentos', ref: SAH(42), categoria: 1, espacos: 1, grupo: 'operacional', especial: ['vestido', 'preso ao braço ou à perna', 'aplica cicatrizante ou medicamento com ação de movimento', 'leva 3 doses, já contadas no espaço', 'carregar uma dose: ação padrão'] },
  { id: 'bracadeira-reforcada', nome: 'Braçadeira Reforçada', ref: SAH(42), categoria: 1, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: '+2 na RD do bloqueio' }], especial: ['vestido'] },
  { id: 'cao-adestrado', nome: 'Cão Adestrado', ref: SAH(42), categoria: 1, espacos: 0, grupo: 'operacional', exigeTreino: 'adestramento', efeitos: [{ alvo: 'pericia', pericia: 'investigacao', valor: 2 }, { alvo: 'pericia', pericia: 'percepcao', valor: 2 }, { alvo: 'defesa', valor: 2, condicional: 'Ladrar e Morder: 1 PE, por 1 rodada' }], especial: ['aliado (regras de aliados: LR p. 170–171)', 'não ocupa espaço (a tabela marca –)'] },
  { id: 'coldre-saque-rapido', nome: 'Coldre Saque Rápido', ref: SAH(42), categoria: 1, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: 'uma vez por rodada, saca ou guarda uma arma de fogo leve como ação livre' }], especial: ['vestido'] },
  { id: 'equipamento-de-escuta', nome: 'Equipamento de Escuta', ref: SAH(42), categoria: 1, espacos: 1, grupo: 'operacional', especial: ['1 receptor (alcance 90 m) e 3 transmissores (captam num raio de 9 m)', 'instalar: alguns minutos e Crime DT 20; o resultado é a DT para achar o transmissor', 'com gente por perto: ação completa, Furtividade contra Percepção e Crime DT +5'] },
  { id: 'estrepes-saco', nome: 'Estrepes (Saco)', ref: SAH(42), categoria: 0, espacos: 1, grupo: 'operacional', especial: ['combate: ação padrão cobre um quadrado de 1,5 m; quem pisa sofre 1d4 de perfuração e fica lento por um dia', 'perseguição: espalhar dá −1d20 no seu teste; o perseguidor que pisar sofre −1d20 nos testes até o fim da cena', 'Reflexos (DT Agi) evita; não afeta quem resiste a todo o seu dano'] },
  { id: 'faixa-de-pregos', nome: 'Faixa de Pregos', ref: SAH(42), categoria: 1, espacos: 2, grupo: 'operacional', especial: ['como estrepes, numa linha de 9 m', 'fura pneus de borracha: o veículo anda à metade'] },
  { id: 'isqueiro', nome: 'Isqueiro', ref: SAH(43), categoria: 0, espacos: 0.5, grupo: 'operacional', especial: ['ação de movimento: chama pequena que acende inflamáveis e ilumina um raio de 3 m'] },
  { id: 'oculos-escuros', nome: 'Óculos Escuros', ref: SAH(43), categoria: 0, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: 'não pode ser ofuscado' }], especial: ['vestido'] },
  { id: 'oculos-de-visao-noturna', nome: 'Óculos de Visão Noturna', ref: SAH(43), categoria: 1, espacos: 1, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: 'enxerga no escuro' }, { alvo: 'resistenciaTeste', dados: -1, condicional: 'contra ofuscado e efeitos de luz' }], especial: ['vestido', 'funciona com bateria'] },
  { id: 'pa', nome: 'Pá', ref: SAH(43), categoria: 0, espacos: 2, grupo: 'operacional', efeitos: [{ alvo: 'nota', texto: '+5 em testes de Força para cavar buracos e mover detritos' }], especial: ['empunhado', 'em combate, conta como um bastão'] },
  { id: 'paraquedas', nome: 'Paraquedas', ref: SAH(43), categoria: 1, espacos: 2, grupo: 'operacional', especial: ['anula o dano de queda', 'sabe usar: veterano em Acrobacia, Pilotagem, Reflexos, Tática ou numa Profissão adequada', 'senão, ou em queda muito curta: Reflexos DT 20; falhou, o dano cai só à metade'] },
  { id: 'traje-de-mergulho', nome: 'Traje de Mergulho', ref: SAH(44), categoria: 1, espacos: 2, grupo: 'operacional', efeitos: [{ alvo: 'resistenciaTeste', valor: 5, condicional: 'contra efeitos ambientais' }, { alvo: 'resistencia', dano: 'quimico', valor: 5 }], especial: ['vestido', 'ocupa o espaço de uma vestimenta', 'vestir ou despir: ação completa', '1 hora de oxigênio'] },
  { id: 'traje-espacial', nome: 'Traje Espacial', ref: SAH(44), categoria: 2, espacos: 5, grupo: 'operacional', efeitos: [{ alvo: 'resistenciaTeste', valor: 10, condicional: 'contra efeitos ambientais' }, { alvo: 'resistencia', dano: 'quimico', valor: 20 }], especial: ['vestido', 'ocupa o espaço de uma vestimenta', 'vestir ou despir: 2 rodadas', '8 horas de água e oxigênio'] },

  // Medicamentos (SaH p. 43)
  { id: 'antibiotico', nome: 'Antibiótico', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '+5 no próximo teste de Fortitude contra doença até o fim do dia'] },
  { id: 'antidoto', nome: 'Antídoto', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '+5 no próximo teste de Fortitude contra veneno até o fim do dia', 'o feito para um veneno específico remove esse veneno'] },
  { id: 'antiemetico', nome: 'Antiemético', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, 'remove enjoado e dá +5 para evitá-lo até o fim da cena'] },
  { id: 'antihistaminico', nome: 'Antihistamínico', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '+5 no próximo teste contra alergia até o fim do dia'] },
  { id: 'anti-inflamatorio', nome: 'Anti-inflamatório', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '1d8+2 PV temporários'] },
  { id: 'antitermico', nome: 'Antitérmico', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, 'novo teste contra uma condição mental; uma vez por cena'] },
  { id: 'broncodilatador', nome: 'Broncodilatador', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '+5 para evitar asfixiado ou fatigado até o fim do dia'] },
  { id: 'coagulante', nome: 'Coagulante', ref: SAH(43), categoria: 1, espacos: 0.5, grupo: 'medicamento', usos: 1, especial: [...MEDICAMENTO, '+5 para se estabilizar de sangrando até o fim do dia', '+5 no teste de Medicina que remove morrendo'] },

  // Itens paranormais (SaH p. 44–45). Catalisadores: um tipo por efeito.
  { id: 'catalisador-ampliador', nome: 'Catalisador Ampliador', ref: SAH(44), categoria: 1, espacos: 0.5, grupo: 'paranormal', usos: 1, especial: [...CATALISADOR, 'alcance do ritual sobe um passo (curto → médio → longo → extremo) ou a área dobra'] },
  { id: 'catalisador-perturbador', nome: 'Catalisador Perturbador', ref: SAH(44), categoria: 1, espacos: 0.5, grupo: 'paranormal', usos: 1, especial: [...CATALISADOR, '+2 na DT para resistir ao ritual'] },
  { id: 'catalisador-potencializador', nome: 'Catalisador Potencializador', ref: SAH(44), categoria: 1, espacos: 0.5, grupo: 'paranormal', usos: 1, especial: [...CATALISADOR, '+1 dado do mesmo tipo no dano do ritual'] },
  { id: 'catalisador-prolongador', nome: 'Catalisador Prolongador', ref: SAH(44), categoria: 1, espacos: 0.5, grupo: 'paranormal', usos: 1, especial: [...CATALISADOR, 'dobra a duração do ritual (não vale para instantâneos nem sustentados)'] },
  { id: 'ligacao-direta-infernal', nome: 'Ligação Direta Infernal', ref: SAH(44), categoria: 2, espacos: 1, grupo: 'paranormal', efeitos: [{ alvo: 'pericia', pericia: 'pilotagem', valor: 5, condicional: 'conduzindo o veículo ligado por ela' }], especial: ['ação completa: dá a partida num veículo, que ganha RD 20 (soma com a que tiver) e imunidade a Sangue', 'falhas em Pilotagem têm consequências ampliadas (em geral, dobradas)', 'remover: ação completa'] },
  { id: 'medidor-de-condicao-vertebral', nome: 'Medidor de Condição Vertebral', ref: SAH(44), categoria: 2, espacos: 1, grupo: 'paranormal', efeitos: [{ alvo: 'pericia', pericia: 'fortitude', valor: 2 }], especial: ['vestido', 'conta como vestimenta', 'conectar: ação completa e deixa atordoado por 1 rodada', 'as cores mostram a saúde; lilás: sob efeito paranormal', '+5 em Medicina para quem cuidar do usuário'] },
  { id: 'pe-de-morto', nome: 'Pé de Morto', ref: SAH(45), categoria: 2, espacos: 1, grupo: 'paranormal', efeitos: [{ alvo: 'pericia', pericia: 'furtividade', valor: 5 }], especial: ['vestido', 'cenas de furtividade (SaH p. 92): ação chamativa só de movimento aumenta a visibilidade em só +1'] },
  { id: 'pen-drive-selado', nome: 'Pen Drive Selado', ref: SAH(45), categoria: 2, espacos: 0.5, grupo: 'paranormal', especial: ['não pode ser invadido nem afetado por rituais, seres ou efeitos de Energia', 'invade outros aparelhos sem ser contaminado'] },
  { id: 'valete-da-salvacao', nome: 'Valete da Salvação', ref: SAH(45), categoria: 1, espacos: 0.5, grupo: 'paranormal', usos: 1, especial: ['consumível', 'ação padrão: voa em alcance médio apontando a melhor rota de fuga e some', 'perseguição (SaH p. 90): sucesso numa ação de cortar caminho'] },

  // Kit exigido pela fabricação em campo (SaH p. 94); categoria e espaço do kit de perícia (LR p. 63).
  { id: 'kit-de-profissao', nome: 'Kit de Profissão', ref: SAH(94), categoria: 0, espacos: 1, grupo: 'kit', kitDe: 'profissao', especial: ['exigido para fabricar itens em campo', 'sem o kit: −5 no teste', 'um por profissão'] },
];
