// Rituais: os 81 do livro de regras (descrições em LR p. 124–143, lista por
// círculo em p. 122–123) e os 16 do Sobrevivendo ao Horror (SaH p. 48–56),
// estes vindos do C.R.I.S e conferidos nas páginas do SaH (o PDF é só
// imagem). Regras gerais em LR p. 117–121: custo de 1, 3, 6 e 10 PE por
// círculo (p. 119), formas avançadas, Custo do Paranormal e rituais de Medo.
//
// Identidade do produto: só nome, números e página, sem descrição.
// Cabeçalho = o do livro (execução, alcance, alvo/área/efeito, duração,
// resistência). Formas: `custoExtra` = PE somados ao custo do círculo;
// `circulo` = poder conjurar rituais desse círculo; `afinidade` = afinidade
// com o elemento do próprio ritual. Forma sem requisito = o livro não pede.
import type { Ref, Ritual } from '../tipos';

const LR = (pagina: number): Ref => ({ fonte: 'LR', pagina });
const SAH = (pagina: number): Ref => ({ fonte: 'SaH', pagina });

export const RITUAIS: Ritual[] = [
  // ================= livro de regras, na ordem do livro =================
  { id: 'alterar-destino', nome: 'Alterar Destino', ref: LR(124), elemento: 'energia', circulo: 4, execucao: 'reacao', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', verdadeiro: { custoExtra: 5 } },
  // o verdadeiro pede 3º círculo num ritual que já é de 3º (assim no livro)
  { id: 'alterar-memoria', nome: 'Alterar Memória', ref: LR(124), elemento: 'conhecimento', circulo: 3, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa', duracao: 'instantânea', resistencia: 'Vontade anula', verdadeiro: { custoExtra: 4, circulo: 3 } },
  // Um ritual só, de 1º círculo em Conhecimento, Energia, Morte e Sangue: o
  // elemento é escolhido ao aprender (LR p. 124). O tipo guarda um elemento;
  // fica o primeiro do cabeçalho.
  { id: 'amaldicoar-arma', nome: 'Amaldiçoar Arma', ref: LR(124), elemento: 'conhecimento', elementos: ['conhecimento', 'energia', 'morte', 'sangue'], circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 arma corpo a corpo ou pacote de munição', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'amaldicoar-tecnologia', nome: 'Amaldiçoar Tecnologia', ref: LR(124), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 acessório ou arma de fogo', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'ancora-temporal', nome: 'Âncora Temporal', ref: LR(124), elemento: 'morte', circulo: 3, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'cena', resistencia: 'Vontade parcial', verdadeiro: { custoExtra: 4, circulo: 4 } },
  { id: 'aprimorar-fisico', nome: 'Aprimorar Físico', ref: LR(125), elemento: 'sangue', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'cena', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'aprimorar-mente', nome: 'Aprimorar Mente', ref: LR(125), elemento: 'conhecimento', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'cena', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  // a descrição dá discente +2 PE; o exemplo de formas avançadas (p. 121) fala em +3
  { id: 'arma-atroz', nome: 'Arma Atroz', ref: LR(125), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 arma corpo a corpo', duracao: 'sustentada', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'armadura-de-sangue', nome: 'Armadura de Sangue', ref: LR(125), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 5, circulo: 3 }, verdadeiro: { custoExtra: 9, circulo: 4, afinidade: true } },
  { id: 'canalizar-o-medo', nome: 'Canalizar o Medo', ref: LR(125), elemento: 'medo', circulo: 4, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa', duracao: 'permanente até ser descarregada' },
  { id: 'capturar-o-coracao', nome: 'Capturar o Coração', ref: LR(125), elemento: 'sangue', circulo: 4, execucao: 'padrao', alcance: 'curto', alvo: '1 pessoa', duracao: 'cena', resistencia: 'Vontade parcial' },
  { id: 'chamas-do-caos', nome: 'Chamas do Caos', ref: LR(126), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'curto', alvo: 'veja texto', duracao: 'cena', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 3 } },
  { id: 'cicatrizacao', nome: 'Cicatrização', ref: LR(126), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 9, circulo: 4, afinidade: true } },
  { id: 'cineraria', nome: 'Cinerária', ref: LR(126), elemento: 'medo', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: 'área: nuvem de 6 m de raio', duracao: 'cena', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'coincidencia-forcada', nome: 'Coincidência Forçada', ref: LR(126), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'compreensao-paranormal', nome: 'Compreensão Paranormal', ref: LR(126), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 ser ou objeto', duracao: 'cena', resistencia: 'Vontade anula (veja texto)', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'conhecendo-o-medo', nome: 'Conhecendo o Medo', ref: LR(127), elemento: 'medo', circulo: 4, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa', duracao: 'cena', resistencia: 'Vontade parcial' },
  { id: 'contencao-fantasmagorica', nome: 'Contenção Fantasmagórica', ref: LR(127), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'medio', alvo: '1 ser', duracao: 'cena', resistencia: 'Reflexos anula', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'consumir-manancial', nome: 'Consumir Manancial', ref: LR(127), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'contato-paranormal', nome: 'Contato Paranormal', ref: LR(127), elemento: 'conhecimento', circulo: 3, execucao: 'completa', alcance: 'pessoal', alvo: 'você', duracao: '1 dia', discente: { custoExtra: 4, circulo: 4 }, verdadeiro: { custoExtra: 9, circulo: 4, afinidade: true } },
  { id: 'controle-mental', nome: 'Controle Mental', ref: LR(128), elemento: 'conhecimento', circulo: 4, execucao: 'padrao', alcance: 'medio', alvo: '1 pessoa ou animal', duracao: 'sustentada', resistencia: 'Vontade parcial', discente: { custoExtra: 5 }, verdadeiro: { custoExtra: 10, afinidade: true } },
  { id: 'convocacao-instantanea', nome: 'Convocação Instantânea', ref: LR(128), elemento: 'energia', circulo: 3, execucao: 'padrao', alcance: 'ilimitado', alvo: '1 objeto de até 2 espaços', duracao: 'instantânea', resistencia: 'Vontade anula', discente: { custoExtra: 4 }, verdadeiro: { custoExtra: 9 } },
  { id: 'convocar-o-algoz', nome: 'Convocar o Algoz', ref: LR(128), elemento: 'morte', circulo: 4, execucao: 'padrao', alcance: '1,5 m', alvo: '1 pessoa', duracao: 'sustentada', resistencia: 'Vontade parcial, Fortitude parcial' },
  { id: 'corpo-adaptado', nome: 'Corpo Adaptado', ref: LR(128), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa ou animal', duracao: 'cena', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'decadencia', nome: 'Decadência', ref: LR(129), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Fortitude reduz à metade', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'definhar', nome: 'Definhar', ref: LR(129), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'cena', resistencia: 'Fortitude parcial', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  // o cabeçalho do livro não traz duração; a explosão é instantânea
  { id: 'deflagracao-de-energia', nome: 'Deflagração de Energia', ref: LR(129), elemento: 'energia', circulo: 4, execucao: 'completa', alcance: 'pessoal', alvo: 'área: explosão de 15 m de raio', duracao: 'instantânea', resistencia: 'Fortitude parcial', verdadeiro: { custoExtra: 5 } },
  { id: 'desacelerar-impacto', nome: 'Desacelerar Impacto', ref: LR(129), elemento: 'morte', circulo: 2, execucao: 'reacao', alcance: 'curto', alvo: '1 ser ou objetos somando até 10 espaços', duracao: 'até chegar ao solo ou cena (o que vier primeiro)', discente: { custoExtra: 3 } },
  { id: 'descarnar', nome: 'Descarnar', ref: LR(129), elemento: 'sangue', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Fortitude parcial', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7, circulo: 3, afinidade: true } },
  { id: 'deteccao-de-ameacas', nome: 'Detecção de Ameaças', ref: LR(130), elemento: 'conhecimento', circulo: 2, execucao: 'padrao', alcance: 'pessoal', alvo: 'área: esfera de 18 m de raio', duracao: 'cena', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 5, circulo: 4 } },
  { id: 'dissonancia-acustica', nome: 'Dissonância Acústica', ref: LR(130), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'medio', alvo: 'área: esfera com 6 m de raio', duracao: 'sustentada', discente: { custoExtra: 1 }, verdadeiro: { custoExtra: 3, circulo: 3 } },
  { id: 'dissipar-ritual', nome: 'Dissipar Ritual', ref: LR(130), elemento: 'medo', circulo: 3, execucao: 'padrao', alcance: 'medio', alvo: '1 ser ou objeto, ou área: esfera com 3 m de raio', duracao: 'instantânea' },
  { id: 'distorcer-aparencia', nome: 'Distorcer Aparência', ref: LR(130), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', resistencia: 'Vontade desacredita', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'distorcao-temporal', nome: 'Distorção Temporal', ref: LR(130), elemento: 'morte', circulo: 4, execucao: 'padrao', alcance: 'pessoal', alvo: 'veja texto', duracao: 'veja texto' },
  { id: 'eco-espiral', nome: 'Eco Espiral', ref: LR(131), elemento: 'morte', circulo: 2, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'até 2 rodadas', resistencia: 'Fortitude reduz à metade', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'eletrocussao', nome: 'Eletrocussão', ref: LR(131), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 ser ou objeto', duracao: 'instantânea', resistencia: 'Fortitude parcial', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'embaralhar', nome: 'Embaralhar', ref: LR(131), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'enfeiticar', nome: 'Enfeitiçar', ref: LR(131), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 pessoa', duracao: 'cena', resistencia: 'Vontade anula', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'esconder-dos-olhos', nome: 'Esconder dos Olhos', ref: LR(132), elemento: 'conhecimento', circulo: 2, execucao: 'livre', alcance: 'pessoal', alvo: 'você', duracao: '1 rodada', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'espirais-da-perdicao', nome: 'Espirais da Perdição', ref: LR(132), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: 'seres escolhidos', duracao: 'sustentada', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 8, circulo: 3 } },
  { id: 'ferver-sangue', nome: 'Ferver Sangue', ref: LR(132), elemento: 'sangue', circulo: 3, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'sustentada', resistencia: 'Fortitude parcial', verdadeiro: { custoExtra: 4, circulo: 4, afinidade: true } },
  { id: 'fim-inevitavel', nome: 'Fim Inevitável', ref: LR(132), elemento: 'morte', circulo: 4, execucao: 'completa', alcance: 'extremo', alvo: 'efeito: buraco negro com 1,5 m de diâmetro', duracao: '3 rodadas', resistencia: 'Fortitude parcial', discente: { custoExtra: 5, afinidade: true }, verdadeiro: { custoExtra: 10, afinidade: true } },
  // o cabeçalho diz Sangue 2 (e a discente pede 3º círculo); a lista por
  // círculo (p. 123) põe no 3º. Fica o do cabeçalho; na dúvida, o mestre decide.
  { id: 'forma-monstruosa', nome: 'Forma Monstruosa', ref: LR(133), elemento: 'sangue', circulo: 2, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 9, circulo: 4, afinidade: true } },
  { id: 'fortalecimento-sensorial', nome: 'Fortalecimento Sensorial', ref: LR(133), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 4, afinidade: true } },
  { id: 'hemofagia', nome: 'Hemofagia', ref: LR(133), elemento: 'sangue', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Fortitude reduz à metade', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'inexistir', nome: 'Inexistir', ref: LR(134), elemento: 'conhecimento', circulo: 4, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Vontade parcial', discente: { custoExtra: 5 }, verdadeiro: { custoExtra: 10, afinidade: true } },
  // na lista por círculo (p. 122) aparece como "Ligação Telepática", um dos dois efeitos
  { id: 'invadir-mente', nome: 'Invadir Mente', ref: LR(134), elemento: 'conhecimento', circulo: 2, execucao: 'padrao', alcance: 'médio ou toque', alvo: '1 ser ou 2 pessoas voluntárias', duracao: 'instantânea ou 1 dia', resistencia: 'Vontade parcial ou nenhuma', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7 } },
  { id: 'involucro-de-carne', nome: 'Invólucro de Carne', ref: LR(134), elemento: 'sangue', circulo: 4, execucao: 'padrao', alcance: 'curto', alvo: 'efeito: 1 clone seu', duracao: 'cena' },
  // só se aprende com o poder de trilha de mesmo nome (Lâmina Paranormal, NEX 99%, LR p. 35)
  { id: 'lamina-do-medo', nome: 'Lâmina do Medo', ref: LR(135), elemento: 'medo', concedidoPor: 'Lâmina Paranormal (NEX 99%)', circulo: 4, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Fortitude parcial' },
  { id: 'localizacao', nome: 'Localização', ref: LR(135), elemento: 'conhecimento', circulo: 2, execucao: 'padrao', alcance: 'pessoal', alvo: 'área: círculo com 90 m de raio', duracao: 'cena', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'luz', nome: 'Luz', ref: LR(135), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 objeto', duracao: 'cena', resistencia: 'Vontade anula (veja texto)', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'medo-tangivel', nome: 'Medo Tangível', ref: LR(135), elemento: 'medo', circulo: 4, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena' },
  { id: 'mergulho-mental', nome: 'Mergulho Mental', ref: LR(136), elemento: 'conhecimento', circulo: 3, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa', duracao: 'sustentada', resistencia: 'Vontade parcial (veja texto)', verdadeiro: { custoExtra: 4, circulo: 4 } },
  { id: 'miasma-entropico', nome: 'Miasma Entrópico', ref: LR(136), elemento: 'morte', circulo: 2, execucao: 'padrao', alcance: 'medio', alvo: 'área: nuvem com 6 m de raio', duracao: 'instantânea', resistencia: 'Fortitude parcial (veja texto)', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 3 } },
  { id: 'nuvem-de-cinzas', nome: 'Nuvem de Cinzas', ref: LR(136), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: 'efeito: nuvem com 6 m de raio e 6 m de altura', duracao: 'cena', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'odio-incontrolavel', nome: 'Ódio Incontrolável', ref: LR(136), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'toque', alvo: '1 pessoa', duracao: 'cena', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'ouvir-os-sussurros', nome: 'Ouvir os Sussurros', ref: LR(137), elemento: 'conhecimento', circulo: 1, execucao: 'completa', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'paradoxo', nome: 'Paradoxo', ref: LR(137), elemento: 'morte', circulo: 2, execucao: 'padrao', alcance: 'medio', alvo: 'área: esfera com 6 m de raio', duracao: 'instantânea', resistencia: 'Fortitude reduz à metade', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'perturbacao', nome: 'Perturbação', ref: LR(137), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 pessoa', duracao: '1 rodada', resistencia: 'Vontade anula', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5, circulo: 3, afinidade: true } },
  { id: 'poeira-da-podridao', nome: 'Poeira da Podridão', ref: LR(138), elemento: 'morte', circulo: 3, execucao: 'padrao', alcance: 'medio', alvo: 'área: nuvem com 6 m de raio', duracao: 'sustentada', resistencia: 'Fortitude (veja texto)', verdadeiro: { custoExtra: 4 } },
  { id: 'polarizacao-caotica', nome: 'Polarização Caótica', ref: LR(138), elemento: 'energia', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: 'você', duracao: 'sustentada', resistencia: 'Vontade anula', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'possessao', nome: 'Possessão', ref: LR(138), elemento: 'conhecimento', circulo: 4, execucao: 'padrao', alcance: 'longo', alvo: '1 pessoa viva ou morta', duracao: '1 dia', resistencia: 'Vontade anula' },
  // o cabeçalho não traz resistência; o texto diz que Vontade reduz os dois danos à metade
  { id: 'presenca-do-medo', nome: 'Presença do Medo', ref: LR(139), elemento: 'medo', circulo: 4, execucao: 'padrao', alcance: 'pessoal', alvo: 'área: emanação de 9 m de raio', duracao: 'sustentada', resistencia: 'Vontade reduz à metade' },
  { id: 'protecao-contra-rituais', nome: 'Proteção contra Rituais', ref: LR(139), elemento: 'medo', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'cena', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 6, circulo: 4 } },
  { id: 'purgatorio', nome: 'Purgatório', ref: LR(139), elemento: 'sangue', circulo: 3, execucao: 'padrao', alcance: 'curto', alvo: 'área: 6 m de raio', duracao: 'sustentada', resistencia: 'Fortitude parcial' },
  { id: 'rejeitar-nevoa', nome: 'Rejeitar Névoa', ref: LR(139), elemento: 'medo', circulo: 2, execucao: 'padrao', alcance: 'curto', alvo: 'área: nuvem de 6 m de raio', duracao: 'cena', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'salto-fantasma', nome: 'Salto Fantasma', ref: LR(139), elemento: 'energia', circulo: 3, execucao: 'padrao', alcance: 'medio', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 4 } },
  { id: 'sopro-do-caos', nome: 'Sopro do Caos', ref: LR(140), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'medio', alvo: 'área: varia', duracao: 'sustentada', resistencia: 'veja texto', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 9 } },
  { id: 'tecer-ilusao', nome: 'Tecer Ilusão', ref: LR(140), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'medio', alvo: 'efeito: ilusão de até 4 cubos de 1,5 m', duracao: 'cena', resistencia: 'Vontade desacredita', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  // o texto também permite conjurar como reação ao sofrer dano (outro efeito)
  { id: 'tela-de-ruido', nome: 'Tela de Ruído', ref: LR(141), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'teletransporte', nome: 'Teletransporte', ref: LR(141), elemento: 'energia', circulo: 4, execucao: 'padrao', alcance: 'toque', alvo: 'até 5 seres voluntários', duracao: 'instantânea', verdadeiro: { custoExtra: 5 } },
  { id: 'tentaculos-de-lodo', nome: 'Tentáculos de Lodo', ref: LR(141), elemento: 'morte', circulo: 3, execucao: 'padrao', alcance: 'medio', alvo: 'área: círculo com 6 m de raio', duracao: 'cena', verdadeiro: { custoExtra: 5 } },
  { id: 'terceiro-olho', nome: 'Terceiro Olho', ref: LR(141), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'transfigurar-agua', nome: 'Transfigurar Água', ref: LR(142), elemento: 'energia', circulo: 3, execucao: 'padrao', alcance: 'longo', alvo: 'área: esfera com 30 m de raio', duracao: 'cena', resistencia: 'veja texto', verdadeiro: { custoExtra: 5 } },
  { id: 'transfigurar-terra', nome: 'Transfigurar Terra', ref: LR(142), elemento: 'energia', circulo: 3, execucao: 'padrao', alcance: 'longo', alvo: 'área: 9 cubos com 1,5 m de lado', duracao: 'instantânea', resistencia: 'veja texto', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'transfusao-vital', nome: 'Transfusão Vital', ref: LR(142), elemento: 'sangue', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea', discente: { custoExtra: 3, circulo: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'velocidade-mortal', nome: 'Velocidade Mortal', ref: LR(142), elemento: 'morte', circulo: 2, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'sustentada', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'videncia', nome: 'Vidência', ref: LR(143), elemento: 'conhecimento', circulo: 3, execucao: 'completa', alcance: 'ilimitado', alvo: '1 ser', duracao: '5 rodadas', resistencia: 'Vontade anula' },
  { id: 'vinculo-de-sangue', nome: 'Vínculo de Sangue', ref: LR(143), elemento: 'sangue', circulo: 4, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'cena', resistencia: 'Fortitude anula' },
  { id: 'vomitar-pestes', nome: 'Vomitar Pestes', ref: LR(143), elemento: 'sangue', circulo: 3, execucao: 'padrao', alcance: 'medio', alvo: 'efeito: 1 enxame Grande (quadrado de 3 m)', duracao: 'sustentada', resistencia: 'Reflexos reduz à metade', discente: { custoExtra: 2 }, verdadeiro: { custoExtra: 5 } },
  { id: 'zerar-entropia', nome: 'Zerar Entropia', ref: LR(143), elemento: 'morte', circulo: 3, execucao: 'padrao', alcance: 'curto', alvo: '1 pessoa', duracao: 'cena', resistencia: 'Vontade parcial', discente: { custoExtra: 4, circulo: 4 }, verdadeiro: { custoExtra: 11, circulo: 4 } },

  // ================= Sobrevivendo ao Horror, na ordem do livro =================
  { id: 'esfolar', nome: 'Esfolar', ref: SAH(48), elemento: 'sangue', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Reflexos parcial', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'sede-de-adrenalina', nome: 'Sede de Adrenalina', ref: SAH(49), elemento: 'sangue', circulo: 2, execucao: 'reacao', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'odor-da-cacada', nome: 'Odor da Caçada', ref: SAH(49), elemento: 'sangue', circulo: 3, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 4 }, verdadeiro: { custoExtra: 9, afinidade: true } },
  { id: 'martirio-de-sangue', nome: 'Martírio de Sangue', ref: SAH(50), elemento: 'sangue', circulo: 4, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'veja texto', discente: { custoExtra: 5, afinidade: true } },
  { id: 'apagar-as-luzes', nome: 'Apagar as Luzes', ref: SAH(50), elemento: 'morte', circulo: 1, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'lingua-morta', nome: 'Língua Morta', ref: SAH(51), elemento: 'morte', circulo: 2, execucao: 'padrao', alcance: 'toque', alvo: '1 cadáver', duracao: 'sustentada', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'fedor-putrido', nome: 'Fedor Pútrido', ref: SAH(52), elemento: 'morte', circulo: 3, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'sustentada', discente: { custoExtra: 4 }, verdadeiro: { custoExtra: 9, afinidade: true } },
  // o cabeçalho do SaH diz só "veja texto" (o C.R.I.S punha Fortitude anula)
  { id: 'singularidade-temporal', nome: 'Singularidade Temporal', ref: SAH(52), elemento: 'morte', circulo: 4, execucao: 'padrao', alcance: 'curto', alvo: '1 objeto não paranormal Médio', duracao: 'instantânea', resistencia: 'veja texto', discente: { custoExtra: 5 }, verdadeiro: { custoExtra: 10 } },
  { id: 'desfazer-sinapses', nome: 'Desfazer Sinapses', ref: SAH(53), elemento: 'conhecimento', circulo: 1, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'instantânea', resistencia: 'Vontade parcial', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'aurora-da-verdade', nome: 'Aurora da Verdade', ref: SAH(53), elemento: 'conhecimento', circulo: 2, execucao: 'padrao', alcance: 'curto', alvo: 'área: esfera com 3 m de raio', duracao: 'sustentada', resistencia: 'Vontade parcial', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4, afinidade: true } },
  { id: 'relembrar-fragmento', nome: 'Relembrar Fragmento', ref: SAH(54), elemento: 'conhecimento', circulo: 3, execucao: 'padrao', alcance: 'toque', alvo: '1 objeto', duracao: 'instantânea', discente: { custoExtra: 4 }, verdadeiro: { custoExtra: 9, afinidade: true } },
  { id: 'pronunciar-sigilo', nome: 'Pronunciar Sigilo', ref: SAH(54), elemento: 'conhecimento', circulo: 4, execucao: 'padrao', alcance: 'curto', alvo: '1 ser', duracao: 'instantânea (veja texto)', resistencia: 'Vontade parcial', discente: { custoExtra: 5 }, verdadeiro: { custoExtra: 10, afinidade: true } },
  { id: 'overclock', nome: 'Overclock', ref: SAH(55), elemento: 'energia', circulo: 1, execucao: 'reacao', alcance: 'pessoal', alvo: 'você', duracao: 'instantânea', discente: { custoExtra: 2, circulo: 2 }, verdadeiro: { custoExtra: 5, circulo: 3 } },
  { id: 'tremeluzir', nome: 'Tremeluzir', ref: SAH(55), elemento: 'energia', circulo: 2, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'sustentada', discente: { custoExtra: 3 }, verdadeiro: { custoExtra: 7, circulo: 4 } },
  { id: 'mutar', nome: 'Mutar', ref: SAH(56), elemento: 'energia', circulo: 3, execucao: 'padrao', alcance: 'pessoal', alvo: 'você', duracao: 'cena', discente: { custoExtra: 4 }, verdadeiro: { custoExtra: 9, afinidade: true } },
  { id: 'milagre-ionizante', nome: 'Milagre Ionizante', ref: SAH(56), elemento: 'energia', circulo: 3, execucao: 'completa', alcance: 'toque', alvo: '1 ser', duracao: 'instantânea' },
];
